name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: npm install -g pnpm

      - name: 'Install dependencies with pnpm'
        run: pnpm install

      - name: 'Build application'
        run: pnpm turbo run build

      - name: Generate Changeset from commit messages
        run: pnpm changeset:autogenerate

      - name: Commit changeset files if present
        run: |
          if [ -d ".changeset" ] && [ "$(ls -A .changeset/*.md 2>/dev/null | wc -l)" -gt 0 ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .changeset/*.md
            git commit -m "ci: autogen changeset [skip ci]" || echo "No changes to commit"
            git push origin HEAD:main
          fi

      - name: Check for changeset files
        id: changeset-check
        run: |
          if [ -d ".changeset" ] && [ "$(ls -A .changeset/*.md 2>/dev/null | wc -l)" -gt 0 ]; then
            echo "chanchangeloggesets=true" >> $GITHUB_OUTPUT
            echo "Found changeset files:"
            ls -la .changeset/*.md
          else
            echo "changesets=false" >> $GITHUB_OUTPUT
            echo "No changeset files found"
          fi

      - name: Create Release Pull Request or Publish to npm
        if: steps.changeset-check.outputs.changesets == 'true'
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip release
        if: steps.changeset-check.outputs.changesets == 'false'
        run: |
          echo "No changeset files found. Skipping release."