name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: npm install -g pnpm

      - name: 'Install dependencies with pnpm'
        run: pnpm install

      - name: Generate Changeset from commit messages
        run: pnpm changeset:autogenerate

      - name: Check for changeset files
        id: changeset-check
        run: |
          if [ -d ".changeset" ] && [ "$(ls -A .changeset/*.md 2>/dev/null | wc -l)" -gt 0 ]; then
            echo "changesets=true" >> $GITHUB_OUTPUT
            echo "Found changeset files:"
            ls -la .changeset/*.md
          else
            echo "changesets=false" >> $GITHUB_OUTPUT
            echo "No changeset files found"
          fi

      - name: Create Release Pull Request or Publish to npm
        if: steps.changeset-check.outputs.changesets == 'true'
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip release
        if: steps.changeset-check.outputs.changesets == 'false'
        run: |
          echo "No changeset files found. Skipping release."
          echo "To create a release, make sure your commits follow the conventional commit format:"
          echo "- feat(scope): description"
          echo "- fix(scope): description"
          echo "- docs(scope): description"
          echo "- chore(scope): description"
          echo "Valid scopes: cli, docs, release, registry, poc" 
